spring:
  data:
    rest:
      base-path: /api


  datasource:
#    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:file:C:/data/sample
    url: jdbc:h2:file:./data/sample
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2

logging:
  file: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.github.fansy: INFO
    org.hibernate: ERROR
server:
  port: 8083